title: Solution Authoring
description: Resources on using SAW to create Cortana Intelligence Solutions.
excerpt_separator: <!--more--> 
theme: minima
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
