title: Solution Authoring
description: Resources on using SAW to create Cortana Intelligence Solutions.
excerpt_separator: \n\n
theme: minima
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

